#include "test.h"

void test_version_string(void);
void test_utf8_ascii_next_prev(void);
void test_utf8_multibyte(void);
void test_utf8_tab_width(void);
void test_utf8_byte_at_col(void);
void test_buffer_empty(void);
void test_buffer_insert_chars(void);
void test_buffer_newlines(void);
void test_buffer_crlf(void);
void test_buffer_split_join(void);
void test_buffer_delete(void);
void test_buffer_load_replace(void);
void test_buffer_span(void);
void test_buffer_split_at_ends(void);
void test_keys_ctrl_q(void);
void test_keys_arrows(void);
void test_keys_ctrl_arrow(void);
void test_keys_home_end_delete(void);
void test_keys_incomplete_esc(void);
void test_keys_utf8_char(void);
void test_screen_put_get(void);
void test_screen_clips(void);
void test_editor_arrows(void);
void test_editor_home_end(void);
void test_editor_goal_column(void);
void test_editor_ctrl_q(void);
void test_editor_handle_arrows(void);
void test_editor_scroll(void);
void test_editor_scroll_view(void);
void test_editor_render(void);
void test_editor_type_and_undo(void);
void test_editor_backspace_delete(void);
void test_editor_backspace_join(void);
void test_editor_enter(void);
void test_editor_word_move(void);
void test_keybind_notepad(void);
void test_keybind_nano(void);
void test_keybind_emacs_prefix(void);
void test_keybind_vi_modes(void);
void test_app_vi_colon_quit(void);
void test_keybind_help_strings(void);
void test_search_find(void);
void test_search_replace_all(void);
void test_wrap_starts(void);
void test_editor_cut_copy_paste(void);
void test_editor_select_all_and_find(void);
void test_editor_replace_all(void);
void test_editor_word_wrap_render(void);
void test_editor_word_wrap_down_insert(void);
void test_editor_word_wrap_down_screen_line(void);
void test_editor_word_wrap_click(void);
void test_editor_wrap_scroll_view(void);
void test_mouse_parse(void);
void test_dialog_type_and_ok(void);
void test_dialog_esc_cancel(void);
void test_dialog_render(void);
void test_app_open_dialog_saveas(void);
void test_app_save_untitled(void);
void test_editor_click(void);
void test_app_mouse_menu(void);
void test_menubar_init(void);
void test_menubar_hotkeys(void);
void test_menubar_hit_bar(void);
void test_menubar_navigate_and_activate(void);
void test_app_menu_exit(void);
void test_app_menu_ctrl_q_exit(void);
void test_app_line_numbers_action(void);
void test_app_render_menu(void);
void test_app_alt_opens_help(void);
void test_settings_defaults(void);
void test_settings_parse_format(void);
void test_settings_roundtrip_file(void);
void test_editor_linenum_toggle(void);
void test_editor_apply_settings(void);
void test_file_read_all(void);
void test_file_read_missing(void);
void test_file_write_and_read(void);
void test_editor_save_roundtrip(void);
void test_editor_save_untitled(void);
void test_editor_new(void);
void test_editor_ctrl_s(void);
void test_cli_no_args(void);
void test_cli_filename(void);
void test_cli_help(void);
void test_cli_version(void);
void test_cli_unknown_option(void);
void test_cli_too_many_files(void);
void test_cli_keys(void);
void test_cli_wrap(void);
void test_kbsel_chars(void);
void test_kbsel_word_right(void);
void test_kbsel_word_left(void);
void test_kbsel_home_end(void);
void test_kbsel_doc_end(void);
void test_kbsel_lines(void);
void test_kbsel_type_replaces(void);
void test_menu_theme_accels(void);
void test_app_theme_switch_updates_accels(void);

int main(void)
{
    const MissNotepadTest tests[] = {
        {"version_string", test_version_string},
        {"utf8_ascii_next_prev", test_utf8_ascii_next_prev},
        {"utf8_multibyte", test_utf8_multibyte},
        {"utf8_tab_width", test_utf8_tab_width},
        {"utf8_byte_at_col", test_utf8_byte_at_col},
        {"buffer_empty", test_buffer_empty},
        {"buffer_insert_chars", test_buffer_insert_chars},
        {"buffer_newlines", test_buffer_newlines},
        {"buffer_crlf", test_buffer_crlf},
        {"buffer_split_join", test_buffer_split_join},
        {"buffer_delete", test_buffer_delete},
        {"buffer_load_replace", test_buffer_load_replace},
        {"buffer_span", test_buffer_span},
        {"buffer_split_at_ends", test_buffer_split_at_ends},
        {"keys_ctrl_q", test_keys_ctrl_q},
        {"keys_arrows", test_keys_arrows},
        {"keys_ctrl_arrow", test_keys_ctrl_arrow},
        {"keys_home_end_delete", test_keys_home_end_delete},
        {"keys_incomplete_esc", test_keys_incomplete_esc},
        {"keys_utf8_char", test_keys_utf8_char},
        {"screen_put_get", test_screen_put_get},
        {"screen_clips", test_screen_clips},
        {"editor_arrows", test_editor_arrows},
        {"editor_home_end", test_editor_home_end},
        {"editor_goal_column", test_editor_goal_column},
        {"editor_ctrl_q", test_editor_ctrl_q},
        {"editor_handle_arrows", test_editor_handle_arrows},
        {"editor_scroll", test_editor_scroll},
        {"editor_scroll_view", test_editor_scroll_view},
        {"editor_render", test_editor_render},
        {"editor_type_and_undo", test_editor_type_and_undo},
        {"editor_backspace_delete", test_editor_backspace_delete},
        {"editor_backspace_join", test_editor_backspace_join},
        {"editor_enter", test_editor_enter},
        {"editor_word_move", test_editor_word_move},
        {"keybind_notepad", test_keybind_notepad},
        {"keybind_nano", test_keybind_nano},
        {"keybind_emacs_prefix", test_keybind_emacs_prefix},
        {"keybind_vi_modes", test_keybind_vi_modes},
        {"app_vi_colon_quit", test_app_vi_colon_quit},
        {"keybind_help_strings", test_keybind_help_strings},
        {"search_find", test_search_find},
        {"search_replace_all", test_search_replace_all},
        {"wrap_starts", test_wrap_starts},
        {"editor_cut_copy_paste", test_editor_cut_copy_paste},
        {"editor_select_all_and_find", test_editor_select_all_and_find},
        {"editor_replace_all", test_editor_replace_all},
        {"editor_word_wrap_render", test_editor_word_wrap_render},
        {"editor_word_wrap_down_insert", test_editor_word_wrap_down_insert},
        {"editor_word_wrap_down_screen_line", test_editor_word_wrap_down_screen_line},
        {"editor_word_wrap_click", test_editor_word_wrap_click},
        {"editor_wrap_scroll_view", test_editor_wrap_scroll_view},
        {"mouse_parse", test_mouse_parse},
        {"dialog_type_and_ok", test_dialog_type_and_ok},
        {"dialog_esc_cancel", test_dialog_esc_cancel},
        {"dialog_render", test_dialog_render},
        {"app_open_dialog_saveas", test_app_open_dialog_saveas},
        {"app_save_untitled", test_app_save_untitled},
        {"editor_click", test_editor_click},
        {"app_mouse_menu", test_app_mouse_menu},
        {"menubar_init", test_menubar_init},
        {"menubar_hotkeys", test_menubar_hotkeys},
        {"menubar_hit_bar", test_menubar_hit_bar},
        {"menubar_navigate_and_activate", test_menubar_navigate_and_activate},
        {"app_menu_exit", test_app_menu_exit},
        {"app_menu_ctrl_q_exit", test_app_menu_ctrl_q_exit},
        {"app_line_numbers_action", test_app_line_numbers_action},
        {"app_render_menu", test_app_render_menu},
        {"app_alt_opens_help", test_app_alt_opens_help},
        {"settings_defaults", test_settings_defaults},
        {"settings_parse_format", test_settings_parse_format},
        {"settings_roundtrip_file", test_settings_roundtrip_file},
        {"editor_linenum_toggle", test_editor_linenum_toggle},
        {"editor_apply_settings", test_editor_apply_settings},
        {"file_read_all", test_file_read_all},
        {"file_read_missing", test_file_read_missing},
        {"file_write_and_read", test_file_write_and_read},
        {"editor_save_roundtrip", test_editor_save_roundtrip},
        {"editor_save_untitled", test_editor_save_untitled},
        {"editor_new", test_editor_new},
        {"editor_ctrl_s", test_editor_ctrl_s},
        {"cli_no_args", test_cli_no_args},
        {"cli_filename", test_cli_filename},
        {"cli_help", test_cli_help},
        {"cli_version", test_cli_version},
        {"cli_unknown_option", test_cli_unknown_option},
        {"cli_too_many_files", test_cli_too_many_files},
        {"cli_keys", test_cli_keys},
        {"cli_wrap", test_cli_wrap},
        {"kbsel_chars", test_kbsel_chars},
        {"kbsel_word_right", test_kbsel_word_right},
        {"kbsel_word_left", test_kbsel_word_left},
        {"kbsel_home_end", test_kbsel_home_end},
        {"kbsel_doc_end", test_kbsel_doc_end},
        {"kbsel_lines", test_kbsel_lines},
        {"kbsel_type_replaces", test_kbsel_type_replaces},
        {"menu_theme_accels", test_menu_theme_accels},
        {"app_theme_switch_updates_accels", test_app_theme_switch_updates_accels},
    };

    return missnotepad_run_tests(tests, (int)(sizeof(tests) / sizeof(tests[0])));
}
